### ISSUE TITLE
[BUG] - Cannot install AtlasOS because Windows Update fails

### ISSUE THREAD

**Issue by MertDalbudak** [Atlas-OS/Atlas#1017]
### Description

With the latest Windows 10 update (KB5034441) which is not installing and resulting into an error (0x80070643) I am not able to install AtlasOS since it requires to install all available Updates first.

### Steps to reproduce

Just run playbook with AME

### Expected behavior

skipping windows update requirements when update couldn't be installed

### Actual behavior

Playbook wants you to update even though update will always result in an error.

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

None specific

**Comment by wozzyi** [comment]
read this,
https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d

**Comment by herocoder14** [comment]
I am pretty sure this is a problem due to the small size of WinRE partition as in newer updates of windows the size of partition should be greater than 750mb.

**Original Problem:**
[Here](https://answers.microsoft.com/en-us/windows/forum/all/kb5034441-update-problem-error-0x80070643/0821b603-9707-4587-9da5-e5809cac3779)

**Solution:**
[Here](https://answers.microsoft.com/en-us/windows/forum/all/resize-recovery-partition/6c5eff50-f3a6-40c3-adc7-97e882452e1a)

**Full Explanation:**
The update KB5034441 failed with a fatal error when staging the WIM. This is due to a lack of free space in the WinRE partition.

[KB5034441: Windows Recovery Environment update for Windows 10, version 21H2 and 22H2: January 9, 2024 - Microsoft Support](https://support.microsoft.com/en-gb/topic/kb5034441-windows-recovery-environment-update-for-windows-10-version-21h2-and-22h2-january-9-2024-62c04204-aaa5-4fee-a02a-2fdea17075a8)

Resizing the Recovery partition to 750 MB resolves the issue. That applies if you use the Windows-default winre.wim.

For OEM-supplied winre.wim (which has additional drivers and packages), ensure the Recovery partition's size is atleast 100 MB more than the size of the custom wim.

KB5028997: Instructions to manually resize your partition to install the WinRE update - Microsoft Support: https://support.microsoft.com/en-us/topic/kb5028997-instructions-to-manually-resize-your-partition-to-install-the-winre-update-400faa27-9343-461c-ada9-24c8229763bf

 

Note: The above MS article works only if your Recovery partition is situated next to (i.e., right side) the OS partition. You can check the disk layout by opening Disk Management.

 

(Based on what I've noticed on the forums, many users have decided to skip/hide the KB5034441 update and wait and see if Microsoft releases a fix.)

**Comment by herocoder14** [comment]
> I am pretty sure this is a problem due to the small size of WinRE partition as in newer updates of windows the size of partition should be greater than 750mb.
> 
> **Original Problem:** [Here](https://answers.microsoft.com/en-us/windows/forum/all/kb5034441-update-problem-error-0x80070643/0821b603-9707-4587-9da5-e5809cac3779)
> 
> **Solution:** [Here](https://answers.microsoft.com/en-us/windows/forum/all/resize-recovery-partition/6c5eff50-f3a6-40c3-adc7-97e882452e1a)
> 
> **Full Explanation:** The update KB5034441 failed with a fatal error when staging the WIM. This is due to a lack of free space in the WinRE partition.
> 
> [KB5034441: Windows Recovery Environment update for Windows 10, version 21H2 and 22H2: January 9, 2024 - Microsoft Support](https://support.microsoft.com/en-gb/topic/kb5034441-windows-recovery-environment-update-for-windows-10-version-21h2-and-22h2-january-9-2024-62c04204-aaa5-4fee-a02a-2fdea17075a8)
> 
> Resizing the Recovery partition to 750 MB resolves the issue. That applies if you use the Windows-default winre.wim.
> 
> For OEM-supplied winre.wim (which has additional drivers and packages), ensure the Recovery partition's size is atleast 100 MB more than the size of the custom wim.
> 
> KB5028997: Instructions to manually resize your partition to install the WinRE update - Microsoft Support: https://support.microsoft.com/en-us/topic/kb5028997-instructions-to-manually-resize-your-partition-to-install-the-winre-update-400faa27-9343-461c-ada9-24c8229763bf
> 
> Note: The above MS article works only if your Recovery partition is situated next to (i.e., right side) the OS partition. You can check the disk layout by opening Disk Management.
> 
> (Based on what I've noticed on the forums, many users have decided to skip/hide the KB5034441 update and wait and see if Microsoft releases a fix.)

**Note:** The explanation is from the official MS site

**Comment by he3als** [comment]
Alternatively, you could try reinstalling using a USB stick and delete all partitions.

**Comment by MertDalbudak** [comment]
I've figured out that pausing Windows Updates enables you to perform the playbook.

**Comment by wicked84** [comment]
thanks Author
[MertDalbudak](https://github.com/MertDalbudak)
