### ISSUE TITLE
[FEATURE] - Supporting voice input

### ISSUE THREAD

**Issue by Designer247** [Atlas-OS/Atlas#1036]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

I wolud like to finish a document through windows 11‘s voice typing (press win+H ), but it told me this function is disabled and is mananged by orginization.
![image](https://github.com/Atlas-OS/Atlas/assets/109426668/025a98c4-6a45-416a-a746-6ad7803fb063)

### Describe the solution you would like.

I hope a new option is added to the atlas desktop folder, to enable it.
Or make it optional in playbook.

### Describe alternatives you have considered.

 I looked for it in gpedit and regedit, but failed to turn it on.

### Additional context.

https://github.com/Atlas-OS/Atlas/assets/109426668/025a98c4-6a45-416a-a746-6ad7803fb063

**Comment by PencilNavigator** [comment]
How is voice input related to gaming? There are obvious privacy issues since voice typing requires sending data to MS servers for STT/VTT, and MS also collects and use your data for their own model training. I'd say not in consideration.  
Use a 3rd party service with better privacy protection.

**Comment by tamalCodes** [comment]
@pencilnav wtf is this logic ? I want AtlasOS + voice typing. 
Is that NOT SOMETHING that atlasos can do ?

**Comment by pencilnav** [comment]
@tamalCodes 
"AtlasOS, or Atlas, is an open-source project that enhances Windows by conveniently applying privacy, usability, and performance optimizations, all while maintaining functionality and [customizability](https://docs.atlasos.net/getting-started/post-installation/atlas-folder/general-configuration/)." - [Source](https://docs.atlasos.net/#what-is-atlasos)

As i mentioned before, `There are obvious privacy issues since voice typing requires sending data to MS servers for STT/VTT, and MS also collects and use your data for their own model training.` Leaving this privacy concerning feature on is something that opposes our project's goals.

>  I want AtlasOS + voice typing.

There are hundreds of privacy focused third party software that can do the same thing. You can try find one to see if it works for you.

If none of it fits your personal needs, you are more than welcome to modify the Atlas Playbook to however you see fit. We open sourced all our scripts, config files, and stuff used for the playbook under our [Github Organization](https://github.com/Atlas-OS). You can find Documentation on how to make a playbook on the [AME Wizard Docs](https://docs.ameliorated.io/), and the [Development Section of our Docs](https://docs.atlasos.net/contributing/playbook/). 

**Please note that we do not offer support for modified playbooks.**
