### ISSUE TITLE
[BUG] - Icloud on windows not working

### ISSUE THREAD

**Issue by Luckickio** [Atlas-OS/Atlas#1040]
### Description

Hello,

When I'm login into Icloud (downloaded from windows store) on my Windows 11 Pro, icloud closes and didn't login…

Advanced data protection is enable on my Icloud Configuration.

I tried on another machine without AltasOS install and it worked.

Sincerely,

Lucas

### Steps to reproduce

1. Install Atlas OS on a fresh windows installation.
2. Maybe Activate advanced data protection on Icloud.
3. Run Icloud for Windows (download from windows store).
5. Try to Loggin.

### Expected behavior

Login Into Icloud

### Actual behavior

Icloud closes and nothing happens.
If I restart Icloud, it asks me to reconnect (it's a loop)...

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Nom de l'appareil	LAPTOP
Processeur	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Mémoire RAM installée	16,0 Go (15,7 Go utilisable)
Type du système	Système d’exploitation 64 bits, processeur x64
Stylet et fonction tactile	Prise en charge du stylet

Édition	Windows 11 Professionnel
Version	23H2
Build du système d’exploitation	22631.3007
Expérience	Windows Feature Experience Pack 1000.22681.1000.0

**Comment by sombreserotonin** [comment]
Neither of my Atlas installs are able to recognise my iPhone when connected via cable either. Windows detects it, but iTunes does not. Not sure if its connected.

**Comment by whallin** [comment]
Are any of the features in iCloud working for you at all? Photos, Drive, etc.?

I've personally been using Atlas (win10 & win11) and iCloud without any problems.

**Comment by Ast3risk-ops** [comment]
Related forum post: https://forum.atlasos.net/d/999-icloud-on-windows-not-working

**Comment by KrDimitrov** [comment]
Might be an issue unrelated to atlas

https://answers.microsoft.com/en-us/windows/forum/all/icloud-crashing-during-login-on-windows-11/660c0483-c16a-4ffc-9eae-cb8b8fcdfaf4

**Comment by NANS05** [comment]
I have the same problem on un fresh install of Atlas on windows 10, icloud not download content end it restart the initial process at all start of the PC

**Comment by CodingMadness** [comment]
> I have the same problem on un fresh install of Atlas on windows 10, icloud not download content end it restart the initial process at all start of the PC

did you have this on fresh windows 10-11 install? Since Dimitrov posted above that it may be also a bug in windows itself, not atlas specific.

**Comment by adam-international** [comment]
There is a workaround in the Atlas Discord, though it's not ideal.

Instead of setting to default, I tried installing iCloud after only disabling any options mentioning telemetry, as well as all of the options under "privacy". This worked for me, but I'm not sure which option actually resolved the problem. 

After installing iCloud, you can re-enable the options and the program works as expected.


**Quote from the Discord server:**
> Download OOShutup10 and select Actions > Undo all changes ("factory defaults") and reboot
>
> Try launching Icloud again
>
> Tell me if it's ok for you, for me it was the problem, Atlas is applying telemetry modifications which are necessary for Icloud to function

[Link to source message](https://canary.discord.com/channels/795710270000332800/1100333602669088789/1206088972929859605)

**Comment by KrDimitrov** [comment]
You can download and use the old, pre UWP icloud, it works for me

**Comment by adam-the** [comment]
Bizarrely enough, for me, this issue was caused by an error related to advertising over Bluetooth. I confirmed that this was the cause of the crash using x64dbg.

To confirm if you are experiencing the same issue and fix it, follow these steps:

1. Attempt to log in to iCloud. It should crash after the 2FA code is entered.
2. Navigate to the logs directory at `C:\Users\{USERNAME}\AppData\Local\Packages\AppleInc.iCloud_nzyj5cx40ttqa\LocalCache\Local\Logs`.
3. Check if the latest `KCCAdp` log file contains a line like this:
`[16448 @ Wed May 08 2024 21:37:50.418]	5776	ERROR	AdvertiseOverBluetooth::StartPublisher	[0x00000154499B6E20-0x1690] serviceProvider_ was reset unexpectedly`.
4. If the line is present, temporarily disable Bluetooth using the tray icon (not the Atlas script).
5. Attempt to log in to iCloud again. This time, it should be successful.

**Comment by he3als** [comment]
Hi, as I can't reproduce this, and the issue does not seem directly related to Atlas, I'm going to close this issue. If there is any information relating to Atlas commented, this issue will be reopened.

**Comment by adam-the** [comment]
> Hi, as I can't reproduce this, and the issue does not seem directly related to Atlas, I'm going to close this issue. If there is any information relating to Atlas commented, this issue will be reopened.

In spite of my previous comment, as far as I'm currently aware, this has only been reproduced in Atlas. Search results relating to the issue bring up this thread and the AtlasOS forum... there must be something being removed from the base Windows installation which iCloud relies on.

Did you test on a device where Bluetooth is present and enabled? Hard to believe you couldn't reproduce it when we have half a dozen people here and on the forum reporting this issue.

**Comment by adam-the** [comment]
Just searched for advertising on the codebase and found this laughable entry: https://github.com/Atlas-OS/Atlas/blob/baeb179b2c99ea8b4e11631965b91f424db06f77/src/playbook/Configuration/tweaks/privacy/advertising/disable-bluetooth-advertising.yml#L4

Re-enabling this registry key fixes the crash issue.

Bluetooth "advertising" is actually just broadcasting very basic information which essentially says "Hey I'm here", which in iClouds case, is telling your other Apple devices to generate a OTP login code, then another to say the login was completed (so the notification can be automatically dismissed)

This configuration entry can be removed outright, it's not a privacy feature, and it will cause issues with other programs which interact with Bluetooth.

**Comment by adam-the** [comment]
@he3als Any update? Please reopen.

**Comment by he3als** [comment]
Bluetooth advertising was re-enabled in v0.4.1 after I went through the Playbook and saw the bad tweak. I haven't been keeping track of this issue, so I didn't respond, sorry

**Comment by adam-the** [comment]
Thanks for the update.
