### ISSUE TITLE
[FEATURE] - Enterprise LTSC Rebase

### ISSUE THREAD

**Issue by Yzrsah** [Atlas-OS/Atlas#1068]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

This feature request thread is intended to discuss the pros and cons of an Atlas variant based on Enterprise LTSC.
Please consider the possibility of a rebase to Enterprise LTSC 24H2. This debloated version of Windows 11 has reduced resource usage.

### Describe the solution you would like.

To make the debloat job easier by starting with a smaller base.

### Describe alternatives you have considered.

.

**Comment by the-P1neapple** [comment]
Firstly, Windows 11 Enterprise LTSC 2024 is not fully released yet so we cannot support you on that basis.

Secondly, due to the fact that the Enterprise versions of Windows is not available (legally) for the regular consumer we choose to not to support it.

However, since this is an open source project, you can modify our playbook to make it compatible. Just don't expect us to provide support or provide any fixes specifically for Enterprise versions.

Thank you for understanding.

**Comment by candrapersada** [comment]
If so, is there still support for Windows 10 Enterprise LTSC?

**Comment by Ast3risk-ops** [comment]
> If so, is there still support for Windows 10 Enterprise LTSC?

We don't support any LTSC editions. Normal Enterprise will work fine.

**Comment by iSavra** [comment]
> > If so, is there still support for Windows 10 Enterprise LTSC?
> 
> We don't support any LTSC editions and never will. Normal Enterprise will work fine.

Was about to open a feature request and found this, I think you should reconsider this, Enterprise LTSC is by a huge margin the best Windows version to start with, you start with less bloat, better performance, better privacy, and all with no security considerations.
Another great perk is extended EOL for Windows 10, which some people still prefer over 11 for a variety of reasons.

I know you have a lot of work to do, but I myself installed Atlas 0.4 on 10 Enterprise LTSC (Forced it by modifying the playbook file), and had no issues so far, so from what I can see, it isn’t so different to the point where it would add too much work.

**Comment by iSavra** [comment]
I can help you test Atlas on Windows 10 Enterprise LTSC, even fresh install, if you’d like just tell me what to look for, as I don’t know how you test new versions.

**Comment by Ast3risk-ops** [comment]
> I can help you test Atlas on Windows 10 Enterprise LTSC, even fresh install, if you’d like just tell me what to look for, as I don’t know how you test new versions.

Can you buy (or even just download) this version legally, from Microsoft, as an individual?

There's your answer as to why official support will never happen.

If you want an OS that is light, with (way) better privacy, (much, *much*) longer support, less security issues, etc, you need to ditch Windows entirely and try Linux (you don't need to pirate it either): https://endof10.org

**Comment by iSavra** [comment]
> Can you buy (or even just download) this version legally, from Microsoft, as an individual?

Depends on who you ask to, if [Microsoft internally used Massgrave](https://www.bleepingcomputer.com/news/security/microsoft-support-cracks-windows-for-customer-after-activation-fails/) and they host their activation scripts (They own GitHub), while they even host the LTSC ISOs, then it's not illegal, their course of action is the only reason why Massgrave still exists to this day, if any of this was against their wishes, they'd Nintendo'd them a long, long time ago.

Atlas OS is a community-owned project independent from Microsoft, the objective is to improve performance for the end-user, whatever the user does before or after applying a config you make has no relation with you or the project, as long as you don't give instructions to do something illegal, otherwise it would be utter insanity. Imagine if a user buys a key from these so-called resellers (Which dare I say: A) most people buying a key will do that B) you can easily buy an Enterprise LTSC that way), then the user applies Atlas OS over it, if you use that logic, you're in trouble, because Atlas OS never made the user swear on their mom that they bought their key through Microsoft or an "authorized" reseller.

**Comment by iSavra** [comment]
> you need to ditch Windows entirely and try Linux

There's no need, Windows is not my main OS, I have it for gaming, tinkering and scenarios where a translation layer isn't good enough.

**Comment by iSavra** [comment]
> Can you buy (or even just download) this version legally, from Microsoft, as an individual?

If your answer to this is yes, then stop supporting Windows Enterprise altogether, **you can't buy or download the full ISO from Microsoft as an individual either**, [it works exactly the same way as LTSC](http://www.microsoft.com/en-us/evalcenter/download-windows-10-enterprise).

**Comment by Ast3risk-ops** [comment]
By the way you linked to the actions of a single support employee which do not reflect Microsoft's views or internal practices in any respect. Enterprise support is also more of a side effect than anything, Atlas targets Pro and Enterprise happens to be similar.

**Comment by iSavra** [comment]
> By the way you linked to the actions of a single support employee which do not reflect Microsoft's views or internal practices in any respect. Enterprise support is also more of a side effect than anything, Atlas targets Pro and Enterprise happens to be similar.

I showed you both, Microsoft has been hosting Massgrave's stuff for years (In addition to letting their methods work). Enterprise LTSC is also similar to Pro, otherwise I would've had issues, and your concern about legality doesn't make any sense whatsoever, as both editions aren't sold to individuals, so I think the only consistent decisions are to either reopen this issue and reconsider support for Enterprise LTSC, or removing support for Enterprise altogether.

**Comment by Ast3risk-ops** [comment]
> > By the way you linked to the actions of a single support employee which do not reflect Microsoft's views or internal practices in any respect. Enterprise support is also more of a side effect than anything, Atlas targets Pro and Enterprise happens to be similar.
> 
> I showed you both, Microsoft has been hosting Massgrave's stuff for years (In addition to letting their methods work). Enterprise LTSC is also similar to Pro, otherwise I would've had issues, and your concern about legality doesn't make any sense whatsoever, as both editions aren't sold to individuals, so I think the only consistent decisions are to either reopen this issue and reconsider support for Enterprise LTSC, or removing support for Enterprise altogether.

Thanks for presenting a false dilemma. If you want to use atlas on LTSC you can, Atlas just won't officially test it.

**Comment by iSavra** [comment]
> > I showed you both, Microsoft has been hosting Massgrave's stuff for years (In addition to letting their methods work). Enterprise LTSC is also similar to Pro, otherwise I would've had issues, and your concern about legality doesn't make any sense whatsoever, as both editions aren't sold to individuals, so I think the only consistent decisions are to either reopen this issue and reconsider support for Enterprise LTSC, or removing support for Enterprise altogether.
> 
> Thanks for presenting a false dilemma. If you want to use atlas on LTSC you can, Atlas just won't officially test it.

You're welcome, but I should mention that it's not really a dilemma, of course you can take another stance, I only said that those two are the only _consistent_ decisions there are, which you know is the case, **that's why you're pretending I didn't just disprove all of your talking points**, and choosing passive aggressiveness over either contributing any substance to this, or just letting someone from the team with more interest consider it.

It's OK, I understand that it's much harder to realize that you're wrong, than to simply make up your mind and ignore that Microsoft's policy for selling and distributing Enterprise and Enterprise LTSC is the same one. You see, I came here in good faith to share some info and to offer my help testing a new edition, but if you're closed-minded and passive-aggressive to a complete stranger from the get-go, it's fine, I can do that as well.

Hey @Xyueta can you please take a look if there's another contributor on a better mood than Asterisk that might be interested in adding support to LTSC?

**Comment by Xyueta** [comment]
Thanks, I'll check it out and let you know
