### ISSUE TITLE
[BUG] - Running"Enable Notifications" doesnt make the settings for Notifications visible ( doesnt edit Registry )

### ISSUE THREAD

**Issue by Evonos** [Atlas-OS/Atlas#1075]
### Description

If you run "Enable Notifications" script it doesnt make the Notifications settings visible in the windows Settings menu because it doesnt remove the "Notifications" entry from the registry key  Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer  **SettingsPageVisibility**

### Steps to reproduce

run "Enable Notifications" 
Open settings
No notification settings even after Restart.

### Expected behavior

See Notification settings ( you enabled the feature via script so you ... want to see it )

### Actual behavior

No Menu.

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Atlas OS 0.4

### Additional content

Fix remove "Notifications" from this entry in registry
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer  **SettingsPageVisibility**  maybe someone could include this into the script

**Comment by thedtvn** [comment]
same

**Comment by thedtvn** [comment]
https://github.com/Atlas-OS/Atlas/assets/80153297/9d480349-cc4d-44bc-a485-cda47d656949

tryed and not work

**Comment by Evonos** [comment]
Restart its unrelated to the issue i posted.

**Comment by thedtvn** [comment]
> Restart its unrelated to the issue i posted.
> 
> 

@Evonos I restart and do all that stuff before I recorded

**Comment by Evonos** [comment]
> > Restart its unrelated to the issue i posted.
> 
> @Evonos I restart and do all that stuff before I recorded

then go on the discord in a support channel , this here is a bug report unrelated to your issue.

**Comment by thedtvn** [comment]
@Evonos is this a bug :/

**Comment by Evonos** [comment]
> @Evonos is this a bug :/

https://discord.gg/jhqdtRv8

**Comment by he3als** [comment]
Scripts in the Atlas folder should say that they're finished, e.g.:

![image](https://github.com/Atlas-OS/Atlas/assets/65787561/0bc3da3e-c718-403a-b559-73a24ec7913c)

If they don't, the script isn't launching, likely due to RunAsTI not functioning.

Can you open a Command Prompt, enter the path to the script, and post the output for troubleshooting, please?

**Comment by Evonos** [comment]
> Scripts in the Atlas folder should say that they're finished, e.g.:
> 
> ![image](https://private-user-images.githubusercontent.com/65787561/322206260-0bc3da3e-c718-403a-b559-73a24ec7913c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjYzNDQsIm5iZiI6MTcxMzAyNjA0NCwicGF0aCI6Ii82NTc4NzU2MS8zMjIyMDYyNjAtMGJjM2RhM2UtYzcxOC00MDNhLWI1NTktNzNhMjRlYzc5MTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE2MzQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOGRiOWEyYTUzOTQyZmFkZWYwMGU0MTE3YzZkMDg2YjEzMmM0MGI0MGMzMTIwMTFiNTllYjdjNTk4ODE5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xmwDYtQTl6cbU7w2JuPKzS7GAQ1h8gflXeH_GdapOaM)
> 
> If they don't, the script isn't launching, likely due to RunAsTI not functioning.
> 
> Can you open a Command Prompt, enter the path to the script, and post the output for troubleshooting, please?

yes it said that , even did run it a 2nd time to make sure ( after reboot after the first time ) both times it said it finished sucessfully.

**Comment by thedtvn** [comment]
@he3als is there a way to fix this like add RunAsTI to Path env or something ?

**Comment by the-P1neapple** [comment]
> is there a way to fix this like add RunAsTI to Path env or something ?

@thedtvn RunAsTI should be added to path by default when running the playbook. You most likely had errors during installation. I would recommend reinstalling your windows as this may have caused a lot of scripts to fail when using the playbook.

Any other questions regarding your issue should be asked in the discord since this is not related to the original post.

**Comment by MuG509** [comment]
Hello, I've encountered the same issue and tried the various solutions displayed in this topic,

@Evonos if you remove the registry keys it allows the notification section on settingspage to  appear back but I any change didnt seem to have any effect,
It appears that even if you run the enable notification script it only enables parts of the notifications back :

"System" notifications (as push notifications) will pop (ex : enable auto HDR)
Apps that integrates a dedicated push notification system will pop (ex : discord PM)

For user installed app that uses the windows notification push system it will not work (ex : whatsapp, tested from store installation)
I believe it is because the service wpnUserService is stopped
I tried to start it back but it refuses to ( tried sfc/ scannow and dism /online /cleanup-image /restorehealth), no result)

I wasn't sure if I disabled notifications when installing so I reinstalled to make sure and got the same result

**Comment by Medullitus** [comment]
Hello. Can you explain to me why you marked this unresolved, ongoing issue as "completed"? @Xyueta @the-P1neapple

**Comment by Evonos** [comment]
> Hello. Can you explain to me why you marked this unresolved, ongoing issue as "completed"? @Xyueta @the-P1neapple

ye i dont get it either its not resolved in any way @Xyueta  why did you solve it solved ? or is it internally fixed ?

**Comment by Xyueta** [comment]
> > Hello. Can you explain to me why you marked this unresolved, ongoing issue as "completed"? @Xyueta @the-P1neapple
> 
> ye i dont get it either its not resolved in any way @Xyueta why did you solve it solved ? or is it internally fixed ?

Yes it is fixed. See commit: https://github.com/Atlas-OS/Atlas/commit/1797068182e8c7e0a477e699cdef61f8dc94ee3b.

Thanks.

**Comment by Xyueta** [comment]
You can check it out by using an action playbook.

**Comment by he3als** [comment]
There's now a new issue for this with workarounds: https://github.com/Atlas-OS/Atlas/issues/1101

For any other workarounds for v0.4, see here: https://github.com/orgs/Atlas-OS/projects/7/views/5
