### ISSUE TITLE
[FEATURE] - Skip branding

### ISSUE THREAD

**Issue by Degl1** [Atlas-OS/Atlas#1115]
### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

Always liked Atlas but I found it was a pain to remove the branding aspect of it as I don't use it. Would like the wallpaper and theme and profile picture and OEM info to be left unchanged. Currently it is just annoying.

### Describe the solution you would like.

Solution would be to have a feature page to skip the branding part

### Describe alternatives you have considered.

I've considered using ReviOS or changing the AtlasOS playbook myself which isn't ideal.

**Comment by the-P1neapple** [comment]
Hello @Degl1,

Our wallpaper and themes are not enforced on Atlas. If you are unable to change this, please ensure you are using an activated Windows installation. 

There is currently an issue with changing profile pictures on Windows 11 at the moment so it may not be possible to change it at this time. Please note this issue is not related to Atlas and is instead present on all Windows 11 installations.

Our use for implementing the OEM information is for the purpose of differentiating what version of our playbook a user has installed for support purposes. This has been the case for assisting with support since 0.2 and have no plans to change this at this time until an alternative way to differentiate versions is available for consideration.

Thank you for understanding.
-Pineapple

**Comment by Degl1** [comment]
I know you can change your wallpaper and all other branding later on. But I'd actually like a full blown switch/featurepage to skip the part where you apply the OEM settings, apply a theme, apply a wallpaper, apply an user profile picture. Moreover the user profile picture can get bugged sometimes and you won't be able to change it.

**Comment by the-P1neapple** [comment]
Hello again,

I have talked about this with the team and we have decided we will not be implementing this feature. I will close this issue now.

Thanks for understanding.

-Pineapple

**Comment by KnightKing777** [comment]
There is problem with changing OEM Informations, some OEM programs/installers requires an specific Manufacturer, Model etc. This "feature" can make some troubles...
