### ISSUE TITLE
[FEATURE] - Make Atlas themes, wallpaper, user icon optional

### ISSUE THREAD

**Issue by AvinashD1010** [Atlas-OS/Atlas#1177]
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### What is your feature request regarding to?

Atlas Playbook

### Is your feature request related to a problem? Please describe.

When applying, updating or reapplying the playbook, the theme, user icon and wallpaper is reset to Atlas OS's default.

### Describe the solution you would like.

I would like Atlas to add an option to opt-out of the theme, wallpaper and user icon installation.

### Describe alternatives you have considered.

I just apply my changes manually everytime.

**Comment by JayXTQ** [comment]
I believe this was already discussed and the answer was no. If anyone higher than me would like to prove me wrong, reopen this and give the answer.

**Comment by JayXTQ** [comment]
Atlas isn't providing bloat by changing some windows settings like wallpaper and user icon, you can change those are Asterisk said above. Bloat typically meaning something that is hard to get rid of, Atlas' resources are really easy to get rid of. I don't even know why you'd consider a wallpaper and user icon bloat? Also, Atlas isn't made to get rid of bloat, it's made to get more performance out of your system, removing bloat can help with that because some of the bloat we remove just runs in the background. A couple megabytes for 2 photos though is really not going to cause a performance decrease. There is no need to complain.

**Comment by he3als** [comment]
The next Atlas release will support upgrading from v0.4 without a Windows reinstall. Upgrades will not overwrite user preferences, such as their current wallpaper.

However, any previous releases have required a [complete Windows reinstall](https://docs.atlasos.net/getting-started/installation/) to upgrade from an older version of Atlas.
