### ISSUE TITLE
A Short Issue Description

### ISSUE THREAD

**Issue by mamalhakir** [Atlas-OS/Atlas#142]
i just installed this os 
i wanna connect to a windows vps so i tried to find "remote desktop connection" as usual but in this os i think its removed
i tried to find the app on internet and download it but i found nothing i think its because of the app is windows 10 default app 
so guys any ideas?

**Comment by Zusier** [comment]
Please read the [wiki](https://github.com/Atlas-OS/Atlas/wiki/1.-FAQ#13-whats-removed-in-atlas-os).

**Comment by MisonL** [comment]
Any way to restore Remote Desktop Services?

**Comment by sharamall** [comment]
This is not mentioned in the repo or on the website. Searching "remote" or searching "terminal" brings up no relevant information. I can understand why Atlas would remove this but it must be documented. It doesn't even need to be configurable in the installation because that's more work for the devs, it just needs to be written down so people can decide whether or not they want to install this software.

I had to reinstall windows because I need RDP server and did not see any evidence that RDP server would be removed. Now that I'm searching issues, the only response is a bad link to a wiki article and issue 356 which says "don't use Atlas." Well I wouldn't have if I would've known...
