### ISSUE TITLE
Bring back "Night light"

### ISSUE THREAD

**Issue by whallin** [Atlas-OS/Atlas#15]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
At the moment, the "Night light" feature part of Windows does not function properly. It is not enabling at all, and it throws an exception breakpoint when trying to enable it manually. I assume this has been removed from the fork mainly to save space and system resources.

**Describe alternatives you've considered**
I've been considering just installing [f.lux](https://justgetflux.com/). While this would definitely be a usable alternative, it'd be handy to still have a night light in Windows itself. One less software for us to download looking for this feature.

**Additional context**
n/a

**Comment by Zusier** [comment]
It just requires a few services, I'll make a script for it. I will post here and on the desktop folder once I make it.

**Comment by Zusier** [comment]
Seems the services do not solve the issue.  For now I've added an alternative to it in [the wiki](https://github.com/Atlas-OS/Atlas/wiki/5.-Software#others). I will keep this issue open, and will look into it further tonight.

**Comment by Zusier** [comment]
Are you still having issues? Will be closing soon.

**Comment by whallin** [comment]
I'm currently using third-party software to achieve this until I have the time to use a proper build with the support implemented.

Feel free to close at your own command.

**Comment by 1011100011111000** [comment]
@Zusier So, night light works on new versions?

**Comment by Zusier** [comment]
Read the issue, it should. If not use thirdparty software as mentionedz

**Comment by CodeCubeNeo** [comment]
I would also like to get the night mode to work. Or to at least add a fix to the Atlas folder? At least how i tested it didn't work

**Comment by Zusier** [comment]
As I mentioned in my previous comment, third party software like f.lux work fine. You should only need graphics drivers for normal night light

**Comment by CodeCubeNeo** [comment]
I have installed my GPU drivers, but LightBulb and normal night light still don't work. F.lux works, but I would want an open source solution, hence the whole atlas OS excellence. Am I still missing something?

**Comment by CodeCubeNeo** [comment]
Hello! I have an update. The thing was that I needed to install the Intel HD graphics drivers (not just the gpu ones). Now the normal night mode still doesn't work, but LightBulb works fine. I would also recommend adding this software to the Atlas desktop folder, since it is also the only way to adjust screen brightness (plus the night light benefits). I would also make a readme.txt where it would be stated that it need the Intel HD graphics, that the "gamma polling" under its setting (third row) should be enabled for non disrupted use and that there is a toogle button for on and off, by clicking the icon in the top left corner of the app (or just point to this link: https://github.com/Tyrrrz/LightBulb/wiki/How-LightBulb-works#lightbulb-dashboard). Really awesome project by the way, this just made it fully usable for me! I am so thankful I am for this!

**Comment by thaynos** [comment]
hey i know that 3rd part solutions exist, but it would really be amazing if native night light could be added. or is it already a part of 22h2?

**Comment by etahamad** [comment]
> 

![image](https://user-images.githubusercontent.com/53538887/222684463-379fe4ed-b126-49c7-94af-a996908820ea.png)
It's already part of 22h2 (unofficial atlas build by me built with latest source commits until now)
