### ISSUE TITLE
Blue screen when shuting down

### ISSUE THREAD

**Issue by Tiorigues** [Atlas-OS/Atlas#360]
Every time i shutdown my laptop it shows me the blue screen, how can i fix it?

**Comment by JayXTQ** [comment]
Never had this issue, and it hasn’t been reported. Can you please follow the template to tell us specs, atlas version, etc.

**Comment by Tiorigues** [comment]
My laptop specs are: 
Intel Atom x5-Z8350;
4GB Ram;
Intel graphic card.
And i am using Atlas 20H2.

**Comment by JayXTQ** [comment]
And can you give us the blue screen error, as it is supposed to give one. Like a code or something to give us an indication of what is causing the bluescreen

**Comment by Tiorigues** [comment]
![PXL_20221205_120303866](https://user-images.githubusercontent.com/100475715/205633572-d847dbae-f23a-407a-b65a-0c6ba8dfa5fe.jpg)

**Comment by PencilNavigator** [comment]
KERNEL_SECURITY_CHECK_FAILURE is mostly due to a graphics card driver or a network card error. Try reinstalling the drivers.
These question are suppose to be in [Discussions](https://github.com/Atlas-OS/Atlas/discussions) or [Discord](https://discord.gg/atlasos), next time when you submit an issue, read the guidelines.

**Comment by PencilNavigator** [comment]
This is not an Atlas issue, so please go ahead and close this since there is only limited support we can give you.
Consider asking in [Discussions](https://github.com/Atlas-OS/Atlas/discussions) or [Discord](https://discord.gg/atlasos).

**Comment by SyrmGIT** [comment]
^ Closing this.
