### ISSUE TITLE
[FEATURE REQUEST] - Keep Windows Defender and related

### ISSUE THREAD

**Issue by Chris6ix** [Atlas-OS/Atlas#704]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

I just learned about Atlas through LTT's video, and it looks really promising, but the fact that Windows Defender will not work is a complete dealbreaker for me, as that is sadly the only antivirus that doesn't suck.

### Describe the solution you would like.

An option to not have Defender disabled would be great.

### Describe alternatives you have considered.

I don't see any alternatives.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by JayXTQ** [comment]
Not going to be added any time soon, sorry. This has been talked about a lot.

**Comment by kevingroeger** [comment]
I'm not very happy with this response. Could you please give some reasoning? 

Defender is a good product, in my opinion, and I would like to have the option to keep it. 

Awesome product btw!

**Comment by gdnzz** [comment]
> I'm not very happy with this response. Could you please give some reasoning? @JayXTQ
> 
> Defender is a good product, in my opinion, and I would like to have the option to keep it.
> 
> Awesome product btw!

 because atlas is gaming focused os, and defender is resource hog. Also you can just use 3rd party alternatives instead.

**Comment by PaulRitzkat** [comment]
Whats a recommended AV these days, besides defender? I think I heard stupid stuff (like crypto, intercepting web traffic for "security", ...) about all of them, even Avira which was "good" in the long gone past...

**Comment by gdnzz** [comment]
> Whats a recommended AV these days, besides defender? I think I heard stupid stuff (like crypto, intercepting web traffic for "security", ...) about all of them, even Avira which was "good" in the long gone past...

Kaspersky free is as effective as defender while being free and less resource hungry

**Comment by kevingroeger** [comment]
> Whats a recommended AV these days, besides defender? I think I heard stupid stuff (like crypto, intercepting web traffic for "security", ...) about all of them, even Avira which was "good" in the long gone past...

Exactly that’s the thing. All the alternatives are bad, in my opinion. 

Thanks for the explanation though, I totally understand that it doesn’t fit into the philosophical of AtlasOS to put in a resource hog. But still, I hope that there will be an option, maybe with a warning attached.

**Comment by Chris6ix** [comment]
> Exactly that’s the thing. All the alternatives are bad, in my opinion.

Exactly my thoughts. They are removing Defender because it's bloat/a resource hog, but then expect you to replace it with some other bloat/resource hog.

IMO, Defender is the least bloated AV Software, and it works just fine. Never had any problems with it.

> I hope that there will be an option one day, maybe with a warning attached.

This I hope, too, because Atlas actually seems really promising.

**Comment by JayXTQ** [comment]
There may be an option to enable defender in the future, also afaik atlas has never suggested downloading your own AV. I don't suggest it because it clogs up system resources. If you really need one use virustotal to scan your files. Just don't download sketchy files. In the future though defender will be **disabled** by default and you can then re-enable it in the future.

**Comment by Chris6ix** [comment]
> If you really need one use virustotal to scan your files. Just don't download sketchy files. 

I know, that the best AV that will ever exist is common sense, so I'm obviously not going to download sketchy files or use virustotal if a file is suspicious, but I still prefer to have Defender active, even if It's just as a peace of mind.

> In the future though defender will be **disabled** by default and you can then re-enable it

Alright, that seems fair.

When you guys add that option, could you just refer to this issue then, so that the people that are subscribed to it (And are interested in this feature) get a notification that you guys added it? Would be greatly appreciated :)

Cheers

**Comment by JayXTQ** [comment]
I will go ahead and make sure in the commit comments that this issue is tagged, lemme just tag it as well on my end so I don't forget because I am very forgetful!

**Comment by Chris6ix** [comment]
> 



> I will go ahead and make sure in the commit comments that this issue is tagged, lemme just tag it as well on my end so I don't forget because I am very forgetful!

Thank you :)

**Comment by BigFreek** [comment]
Have you guys tried other free virus protection?

**Comment by solisinvictum** [comment]
Dont want to start a flamewar, about Defender.

I just found out about AtlasOS from cachyos discord channel. 

I dont have a use for something like that. Especially because of Security conserns.

Atleast Defender should be left enabled by default. The Argument about Performance/Bloat/what ever is inconsistent. Alone if you give the Source a look, and find out that things like bitlocker is still enabled.

And the Claim on the Frontpage of this repo, that AtlasOS is more secure, isnt true too. 

You dont get Viruses/malware/trojans/what_ever only with infected Files. Most Systems get infected over recieving emails and by visiting normal broad common websites over infected frameworks and javascripts for example.

Its not uncommon that somebody for example visit the Website of they regional Newspaper, and get infected with shit.

But nvm. I have free time and im bored.

Cloned the Source. I spin a VM up and create a patch/script to enable Windows Defender again at default stage and settings.

If im done. Im post here again.

Sry for my english. Im not a native speaker.

**Comment by JayXTQ** [comment]
Atlas won't enable defender by default, but we will have it disabled by default in the future. Reason why it won't be enabled is because of performance, many people get a huge performance boost having it disabled/removed.

**Comment by gdnzz** [comment]
@solisinvictum You don't need to start, there is already one going on. People just ran into atlas in LTT's video, and now everyone is denigrating atlas because it doesn't have defender. Purpose of atlas has already been gaming for years, and defender is a resource hungry background process, that's why it is removed. However, people are just downloading atlas now without reading anything about it and complaining why atlas removes defender and some other security features. So lets assume defender is added back, what about updates, or let's just make atlas same as windows? Oh lets also keep fax, dial up and some other features a few people use. You can't really make it work almost x2 better than windows without removing anything or disabling some things. There is no magic wand.

**Comment by solisinvictum** [comment]
@gdnzz where? maybe i can cooperate with them.

@JayXTQ everything else, could be left like it is now. But because you likely now, every gaming machine today, and thats is more true for people who wanna use atlasos, are online.

And they use atleast one Store/launcher/what_ever. With them they download games.

it isnt the first time, and totaly not uncommon, to deploy viruses for example over steam. it happend already dozen times. Most of the time, because they content server got hacked or the accounts from the devs of a game. You could google it by your self.

So, if you guys totaly dont want to have defender by default ON (because the user should be asked if he understand the risks, even if they are low), you should atleast write on the first page of your homepage, github, wiki etc, that these modification of windows makes windows totaly unsecure to use with a internet connection, and that the user is totaly self aware and responsible for his machine and the security of it and his data. 

That is the bare minimum.

**Comment by JayXTQ** [comment]
Yes, we will tell people that defender is disabled by default, don't you worry. I will make sure of it as the docs writer

**Comment by JayXTQ** [comment]
UAC being disabled is already documented, but this isn't about UAC.

**Comment by solisinvictum** [comment]
Yes, like i said. But it is very unlikely that your audience read that directly (most of them would join discord maybe and ask there why they have xyz problem, where they get the link to the documentation as answer).

And in the Installprocess with that playbook, there isnt one time mentioned what actually happens. 

It would be good, to inform the User than to read the documentation first.

**Comment by gdnzz** [comment]
There is already spectre prompt, and people have been asking it all the time on discord. It would even be more confusing if the wizard prompted you about every change on the system. They already in the docs and you can configure it after install.

**Comment by daBroma** [comment]
Best AV:
1. Common sense
2. Scan suspicious files with VirusTotal
3. Do MalwareBytes scans monthly
4. ESET
Enjoy. No real reason to use an AV nowadays if you're semi competent with computers.

**Comment by JayXTQ** [comment]
It's hard to do that when we totally deleted defender, there is no way to add it back afaik. In the future there will be a way to disable/enable it as I said multiple times, heck we may even give you the choice during installation if you want it or not.

**Comment by mathiasmupschi** [comment]
also, is there a way to completely undo all the changes or do i have to reinstall windows?

**Comment by Chris6ix** [comment]
@gdnzz 
>  You don't need to start, there is already one going on. People just ran into atlas in LTT's video, and now everyone is denigrating atlas because it doesn't have defender. Purpose of atlas has already been gaming for years, and defender is a resource hungry background process, that's why it is removed. However, people are just downloading atlas now without reading anything about it and complaining why atlas removes defender and some other security features. So lets assume defender is added back, what about updates, or let's just make atlas same as windows? Oh lets also keep fax, dial up and some other features a few people use. You can't really make it work almost x2 better than windows without removing anything or disabling some things. There is no magic wand.

Goddamn, pull the stick out of your ass.
No, not 
> everyone is denigrating atlas because it doesn't have defender

We are just ASKING for an OPTION to not have Defender removed, because some of us are fine with trading in a bit of the performance improvement that Atlas offers for an AV.
>  defender is resource hungry

Yes, very
![image](https://user-images.githubusercontent.com/65610536/234646192-a9c33ab4-8098-4c66-91e4-8b4a8a4d3c20.png)

Just as a comparison, Steam just displaying the Library, without doing anything:

![image](https://user-images.githubusercontent.com/65610536/234646530-0dc7d400-94e0-48ec-8e3e-24cde373130e.png)

But sure, Defender is resource hungry...

> However, people are just downloading atlas now without reading anything about it and complaining why atlas removes defender and some other security features.

Just straight up wrong. You even conflict yourself here with your previous sentence:

> People just ran into atlas in LTT's video

We saw LTT's video, where Atlas's downsides were displayed like this:
![image](https://user-images.githubusercontent.com/65610536/234647797-31d0a7bb-806d-41fd-9e68-5a8a27301f9e.png)

And I decided to come to the repo and ASK for an OPTION to keep Defender.

> So lets assume defender is added back, what about updates, or let's just make atlas same as windows? Oh lets also keep fax, dial up and some other features a few people use. You can't really make it work almost x2 better than windows without removing anything or disabling some things. There is no magic wand.

Literally no one has said anything like that. We are not holding a gun to the devs heads and telling them to re-add all the features they stripped out. We are ASKING if we could have an OPTION to keep 1 program, that some of us like to have, Defender.
@JayXTQ even said that they will keep Defender disabled by default and give us the OPTION to enable it in the future.
If you don't like Defender, then just don't touch that OPTION.

Stop putting words in people's mouths and crying about something that wasn't even said.

Thank you.

@JayXTQ if you want, please lock this issue to collabs only, so that people stop writing nonsense here and spamming everyone that is subscribed with notifications. 
Thanks in advance, since I won't be able to thank you once it's done ;)

**Comment by JayXTQ** [comment]
Adding again onto here, I will be locking the post from here on out but I want to clarify something.

What I personally feel that should happen with this:

- People get the option to keep defender or get it removed inside of the Playbook, as a choice, like how disabling/enabling Spectre and Meltdown is done before Atlas installs
- This would allow people to not have defender on their system if they don't want it (people like me)
- For the people who do want it, they can agree to having it on their system in the AME Wizard and then they will have the choice of disabling/enabling it whenever and wherever.

What I think might be best for Atlas because I know many people dislike Defender but here is what is most likely to happen:
- Atlas will reinstate Defender as a whole
- AME disables it at the start, Atlas will keep it disabled when Atlas is loaded
- The user can enter the Atlas folder and enable Defender within the configuration files
- They can also disable whenever and wherever they want.

Hope this clears everything up, and I hope everyone here has a great day!

**Comment by he3als** [comment]
https://github.com/Atlas-OS/Atlas/tree/defender-toggle

Although not merged to main branches yet, Defender has been added back (as an optional feature) and is functional enough to the point where this issue can be deemed as completed.
