### ISSUE TITLE
[FEATURE REQUEST] - Remove this.

### ISSUE THREAD

**Issue by h4rldev** [Atlas-OS/Atlas#909]
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

Atlas OS is a mistake, not only does it make your system vulnerable, it does things that you can do by yourself in seconds.

Atlas shouldn't exist since it's literally just a bad way to debloat windows, often breaking things due to people sucking at batch 💀
If you want a debloater that works, use something that doesn't remove things that cause problems with programs and maybe learn something else.

### Describe the solution you would like.

Convert AtlasOS to Just Atlas, and create a tool that can generate a debloated iso based on user choice, or make it a debloat tool that you run to debloat a bloated system.

### Describe alternatives you have considered.

Instead of wasting your time on security vulnerabilities

Use these:
[bloatbox](https://github.com/builtbybel/bloatbox) (windows 10)
[BloatyNosy](https://github.com/builtbybel/BloatyNosy) (windows 11)

They're simply way safer.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Additional context.

I sincerely don't care if you get angry or whatever. Just stop swindling people that this is a good project.

**Comment by JayXTQ** [comment]
No. Atlas will stay as is. We are fixing all issues for 0.3. If you hate atlas. Don't use it. No need to do shit like this which isn't useful what so ever. Useless comments.

**Comment by sabaasa** [comment]
> not only does it make your system vulnerable

???

**Comment by he3als** [comment]
> not only does it make your system vulnerable, it does things that you can do by yourself in seconds

Atlas has 180+ playbook files with hundreds and hundreds of tweaks, you can't do that by yourself in seconds. Additionally, Atlas aims to only have effective tweaks and people trying to replicate what Atlas does from scratch with no knowledge would have a hard time.

Security is a concern for v0.2.0, but as stated on the documentation and shown by the commits/progress since, v0.3.0 will have  **(and already has on the Git)** Windows Update and Windows Defender for users that want them.

> often breaking things due to people sucking at batch 💀

Other tweaking tools are also problematic, if generally not more problematic than what v0.3.0 will be. v0.3.0 will have extensive testing and has had over 950 commits to fix issues. Yes, stability and bugs are prevalent in v0.2.0, but that's not going to be the case for v0.3.0.

> Convert AtlasOS to Just Atlas, and create a tool that can generate a debloated iso based on user choice

This might be an option in the future alongside the current system. ISOs were dropped as distributing them is against the Windows EULA, as well as being much less trustworthy.

> Just stop swindling people that this is a good project.

We've *never* ourselves claimed that AtlasOS is literally the best project in existence. Keep in mind that Atlas is still in beta and is only currently at the v0.2.0 milestone.

---

This issue was overall rude and lazily made. If you had researched into the current development, then you would of known that lots of your points are no longer problems, and **that your issue is basically spam**.
